name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@master
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: chabad360/hugo-gh-pages@master
      with:
        hugoVersion: 0.69.2
        repo: sblaizerwize/intermine-docs
        githubToken: ${{ secrets.HUGO_TOKEN }}
        cname: intermine-docs
        args: --gc --minify --cleanDestinationDir
